//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Espor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class blog
    {
        public int ID { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public int queue { get; set; }
    }
}
